config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root "static_pages#home"
  get "static_pages/about"

  resources :users do
    resources :questions
  end
  resources :exams

  namespace :admin do
    root "users#index"
    resources :exams, only: [:show, :index, :destroy, :update]
    resources :questions
    resources :users
    resources :subjects
    resources :activities, only: [:index]
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  enum status: [:waitting, :accept]
  enum question_type: [:single, :multiple, :text]
  belongs_to :subject
  belongs_to :user

  has_many :answers, dependent: :destroy
  has_many :results, dependent: :destroy
  has_many :exams, through: :results
  scope :latest, ->{order created_at: :desc}

  accepts_nested_attributes_for :answers, allow_destroy: true,
    reject_if: proc {|answer| answer[:content].blank?}

  validates :content, presence: true
  validates :answers, presence: true
  before_create :init_status

  private
  def init_status
    self.status = :waitting if status.nil?
  end

end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < ApplicationController
  load_and_authorize_resource

  def index
    @questions = @questions.latest.page(params[:page]).per 15
  end

  def show
    @answers = @question.answers
  end

  def new
    @subjects = Subject.all
    @question.answers.build
  end

  def create
    @question = Question.new question_params
    if @question.save
      flash[:success] = t "admin.question.flash_create_question_success"
      redirect_to admin_questions_path
    else
      flash[:error] = t "admin.question.flash_create_question_fail"
      render :new
    end
  end

  def edit
    @subjects = Subject.all
    @question.answers.build
  end

  def update
    if @question && @question.update_attributes(question_params)
      flash[:success] = t "admin.question.flash_update_question_success"
      redirect_to admin_questions_path current_user
    else
      flash[:danger] = t "admin.question.flash_update_question_fail"
      render :edit
    end
  end

  def destroy
    if @question.destroy
      flash[:success] = t "admin.question.flash_destroy_question_success"
    else
      flash[:danger] = t "admin.question.flash_destroy_question_fail"
    end
    redirect_to admin_questions_path
  end

  private
  def question_params
    params.require(:question).permit :question_type, :content, :subject_id,
      :user_id, :status, answers_attributes: [:id, :is_correct, :content, :_destroy]
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  load_and_authorize_resource

  def show
    @answers = @question.answers
  end

  def index
    @questions = current_user.questions
  end

  def new
    @subjects = Subject.all
    @question.answers.build
  end

  def create
    @question = Question.new question_params
    if @question.save
      flash[:success] = t "questions.flash.success"
      redirect_to user_questions_path
    else
      flash[:error] = t "questions.flash.create_fail"
      render :new
    end
  end

  def edit
    @subjects = Subject.all
    @question.answers.build
  end

  def update
    if @question&.update_attributes(question_params)
      flash[:success] = t ".success"
      redirect_to user_questions_path current_user
    else
      flash[:danger] = t ".error"
      render :edit
    end
  end

  def destroy
    if @question.destroy
      flash[:success] = t ".success"
    else
      flash.now[:danger] = t ".error"
    end
    redirect_to user_questions_path
  end

  private
  def question_params
    params.require(:question).permit :question_type, :content, :subject_id,
      :user_id, :status, answers_attributes: [:id, :is_correct, :content, :_destroy]
  end

end

app/views/questions/_form.html.erb
<%= form_for [current_user, @question] do |f| %>
  <%= render "shared/errors", object: f.object %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :status, value: :waitting %>

  <%= f.label :subject %>
  <%= f.select :subject_id,
    options_from_collection_for_select(@subjects, :id, :name, params[:subject_id]),
    {}, {class: "form-control"} %>

  <%= f.label :content %>
  <%= f.text_area :content, class: "form-control" %>

  <%= f.label :question_type %>
  <%= f.select :question_type, Question.question_types.keys.to_a, {},
    {class: "form-control"} %>

  <%= f.label :option %>
  <div id="choice">
    <div id="answers">
      <%= f.fields_for :answers do |answer| %>
        <div class="answers">
          <%= render "answer_form", f: answer %>
        </div>
      <% end %>
    </div>
    <div class="col-md-offset-0 col-md-3">
      <%= link_to_add_fields raw("#{t :add}"), f, :answers %>
      <br>
    </div>
  </div>

  <div class="row">
    <%= f.submit t("questions.new.btn_create"), class: "btn btn-primary col-md-3" %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h2><b><%= t "questions.index.title" %></b></h2>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/questions/index.html.erb
<div class="content container">
  <div class="col-md-10 col-md-offset-1 width-flash">
  </div>
  <div class="row" id="question">
    <div class="col-md-10 col-md-offset-1">
      <h1>
        <b><%= t ".title" %></b>
        <%= link_to t(".new_q"), new_user_question_path,
          class: "pull-right link-text-question" %>
      </h1>
      <table class="table">
        <thead>
          <tr>
            <th class="number_id"><%= t ".stt" %></th>
            <th class="content"><%= t ".question" %></th>
            <th class="subject"><%= t ".subject" %></th>
            <th class="type"><%= t ".type" %></th>
            <th class="state"><%= t ".state" %></th>
            <th class="action"></th>
          </tr>
        </thead>
        <tbody>
          <% @questions.each do |question| %>
            <tr>
              <td><%= question.id %></td>
              <td>
                <%= link_to question.content,
                  user_question_path(current_user, question) %>
              </td>
              <td><%= question.subject.name %></td>
              <td><%= question.question_type %></td>
              <td><span class="label label-warning"><%= question.status %></span></td>
              <td>
                <%= link_to edit_user_question_path(current_user, question) do %>
                  <i class="glyphicon glyphicon-edit"></i>
                <% end %>
                <%= link_to user_question_path(current_user, question),
                  method: :delete, data: {confirm: "are you sure?"} do %>
                  <i class="glyphicon glyphicon-trash"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/questions/new.html.erb
<h1><b><%= t "questions.index.title" %></b></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [current_user, @question] do |f| %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.hidden_field :status, value: :waitting %>

      <%= f.label :subject %>
      <%= f.select :subject_id,
        options_from_collection_for_select(@subjects, :id, :name, params[:subject_id]),
        {}, {class: "form-control"} %>

      <%= f.label :content %>
      <%= f.text_area :content, class: "form-control" %>

      <%= f.label :question_type %>
      <%= f.select :question_type, Question.question_types.keys.to_a, {},
        {class: "form-control"} %>

      <%= f.label :option %>
      <div id="choice">
        <div id="answers">
          <%= f.fields_for :answers do |answer| %>
            <div class="answers">
              <%= render "answer_form", f: answer %>
            </div>
          <% end %>
        </div>
        <div class="col-md-offset-0 col-md-3">
          <%= link_to_add_fields raw("#{t :add}"), f, :answers %>
          <br>
        </div>
      </div>

      <div class="row">
        <%= f.submit t(".btn_create"), class: "btn btn-primary col-md-3" %>
      </div>
    <% end %>
  </div>
</div>

app/views/questions/show.html.erb
<h2><b><%= t ".title" %></b></h2>
<div class="row col-md-offset-3">
  <table class="table borderless">
    <tbody>
      <tr>
        <td class="title"><%= t ".content" %></td>
        <td><%= @question.content %></td>
      </tr>
      <tr>
        <td class="title"><%= t ".option" %></td>
        <td>
          <table id="table-show-render">
            <% @answers.each do |answer| %>
              <tr>
                <% if answer.is_correct? %>
                  <td>
                    <span class="label label-primary">Correct</span>
                  </td>
                <% else %>
                  <td>
                    <span class="label label-danger">wrong</span>
                  </td>
                <% end %>
                <td><%= answer.content %></td>
              </tr>
            <% end %>
          </table>
        </td>
      </tr>
      <tr>
        <td class="title"><%= t "question.index.subject" %></td>
        <td><%= @question.subject.name %></td>
      </tr>
      <tr>
        <td class="title"><%= t ".question_type" %></td>
        <td><div><%= @question.question_type %></div></td>
      </tr>
      <tr>
        <td class="title"><%= t "question.index.state" %></td>
        <td><div class="state-label label label-warning"><%= @question.status %></div></td>
      </tr>
      <tr>
        <td>
          <%= link_to edit_user_question_path(current_user, @question) do %>
            <i class="btn btn-primary glyphicon glyphicon-pencil btn-width"><%= t ".btn_edit" %></i>
          <% end %>
          <%= link_to user_question_path(current_user, @question),
            method: :delete, data: {confirm: "are you sure?"} do %>
            <i class="btn btn-danger glyphicon glyphicon-trash btn-width"><%= t ".btn_del" %></i>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
</div>