config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root "static_pages#home"
  get "static_pages/about"

  resources :users do
    resources :questions
  end
  resources :exams

  namespace :admin do
    root "users#index"
    resources :exams, only: [:show, :index, :destroy, :update]
    resources :questions
    resources :users
    resources :subjects
    resources :activities, only: [:index]
  end
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  has_many :exams, dependent: :destroy
  has_many :questions, dependent: :destroy

  validates :name, presence: true, length: {maximum: 100}
end

app/controllers/admin/subjects_controller.rb
class Admin::SubjectsController < ApplicationController
  load_and_authorize_resource

  def index
    @subjects = @subjects.page params[:page]
  end

  def update
    if @subject.update_attributes subject_params
      flash[:success] = t "admin.subject.flash_update_success"
      redirect_to admin_subjects_path
    else
      flash[:danger] = t "admin.subject.flash.flash_update_fail"
      render :edit
    end
  end

  def create
    if @subject.save
      SubjectNotifierUser.new.mail_to_user_when_create @subject
      flash[:success] = t "admin.subject.new_subject_success"
      redirect_to admin_subjects_path
    else
      flash[:danger] = t "admin.subject.new_subject_fail"
      render :new
    end
  end

  def destroy
    if @subject.destroy
      flash[:success] = t "admin.subject.destroy_success"
    else
      flash[:danger] = t "admin.subject.destroy_fail"
    end
    redirect_to admin_subjects_path
  end

  private
  def subject_params
    params.require(:subject).permit :name
  end
end

app/views/admin/subjects/edit.html.erb
<% provide :title, t("admin.subject.edit") %>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h2><%= t "admin.subject.edit_subject" %></h2>
    <%= form_for [:admin, @subject] do |f| %>
      <%= render "shared/errors", object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control", placeholder: t("admin.subject.text_placeholder") %>
      <%= f.submit t("admin.subject.submit"), class: "btn btn-primary new_subject" %>
    <% end %>
  </div>
</div>

app/views/admin/subjects/index.html.erb
<% provide :title, t("admin.subject.title.index") %>
<div class="row">
  <div class="col-md-12">
    <h2>
      <b><%= t "admin.subject.title.index" %></b>
      <%= link_to new_admin_subject_path, class: "btn btn-primary pull-right" do %>
        <span class="glyphicon glyphicon-plus"></span>
        <%= t "admin.subject.new_subject" %>
      <% end %>
    </h2>
    <table class="table">
      <thead>
        <tr>
          <th class="stt"><%= t "admin.subject.table.stt" %></th>
          <th class="subject_name"><%= t "admin.subject.table.subject_name"%></th>
          <th class="created_at"><%= t "admin.subject.table.created_at" %></th>
          <th class="view"><%= t "admin.subject.table.view" %></th>
          <th class="edit"><%= t "admin.subject.table.edit" %></th>
          <th class="delete"><%= t "admin.subject.table.delete" %></th>
        </tr>
      </thead>
      <tbody>
        <% @subjects.each_with_index do|subject, index| %>
          <tr>
            <td><%= index + 1 %></td>
            <td><%= subject.name %></td>
            <td><%= subject.created_at.strftime("%Y/%m/%d") %></td>
            <td><%= link_to t("admin.subject.view"), admin_subject_path(subject), class: "btn btn-primary" %></td>
            <td><%= link_to t("admin.subject.edit"), edit_admin_subject_path(subject),
              class: "btn btn-primary" %></td>
            <td><%= link_to t("delete"), [:admin, subject], method: :delete,
              data: {confirm: t("application.general.confirm_delete")},
              class: "btn btn-danger glyphicon glyphicon-trash btn-width" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @subjects %>
  </div>
</div>

app/views/admin/subjects/new.html.erb
<% provide :title, t("admin.subject.new") %>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h2><b><%= t "admin.subject.new" %></b></h2>
    <%= form_for [:admin, @subject] do |f| %>
      <%= render "shared/errors", object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control", placeholder: t("admin.subject.text_placeholder") %>
      <%= f.submit t("admin.subject.submit"), class: "btn btn-primary new_subject" %>
    <% end %>
  </div>
</div>

app/views/admin/subjects/show.html.erb
<% provide :title, t("admin.subject.title.show") %>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h2><%= t "admin.subject.subject_detail" %></h2>
    <table class="table">
      <tr>
        <td><strong><%= t "admin.subject.table.name" %></strong></td>
        <td><%= @subject.name %></td>
      </tr>
      <tr>
        <td><strong><%= t "admin.subject.table.created_at" %></strong></td>
        <td><%= @subject.created_at.strftime("%Y/%m/%d") %></td>
      </tr>
      <tr>
        <td><strong><%= t "admin.subject.table.number_exams" %></strong></td>
        <td><%= @subject.exams.size %></td>
      </tr>
    </table>
  </div>
</div>