config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root "static_pages#home"
  get "static_pages/about"

  resources :users do
    resources :questions
  end
  resources :exams

  namespace :admin do
    root "users#index"
    resources :exams, only: [:show, :index, :destroy, :update]
    resources :questions
    resources :users
    resources :subjects
    resources :activities, only: [:index]
  end
end

app/models/exam.rb
class Exam < ActiveRecord::Base
  TIME_PER_EXAM = 28800

  enum status: [:start,:testing, :unchecked,:checked]

  belongs_to :subject
  belongs_to :user
  has_many :results, dependent: :destroy
  has_many :questions, through: :results

  accepts_nested_attributes_for :results

  before_create :init_exam
  after_update :send_exam_message
  after_create :delay_exam_create

  def change_status_after_start
    if self.start?
      self.status = :testing
      self.started_at = Time.zone.now.to_i
      self.calculate_time
      self.save
    end
  end

  def calculate_time
    self.spent_time = Time.zone.now.to_i - self.started_at
  end

  def time_remain
    self.duration*60 - self.spent_time
  end

  def send_exam_message
    HardWorker.perform_async self.id if self.checked?
  end

  def check_time_exam
    if (Time.zone.now - self.created_at).to_i >= Exam::TIME_PER_EXAM
      return true
    else
      return false
    end
  end

  def delay_exam_create
    if check_time_exam && self.start?
      UserNotifier.delay_exam_when_create(self).deliver_now
    end
  end
  handle_asynchronously :delay_exam_create, run_at: Proc.new { 8.hours.from_now }

  def send_statistic_exam_email
    @exam.all do |exam|
      UserNotifier.send_email_every_month(exam).deliver_now
    end
  end

  private
  def init_exam
    self.spent_time = 0
    @questions = self.subject.questions.accept.order("RANDOM()").
      limit(Settings.exam.number_of_question)
    @questions.each do |question|
      self.results.build question_id: question.id
    end
  end

end

app/controllers/admin/exams_controller.rb
class Admin::ExamsController < ApplicationController
  load_and_authorize_resource

  def index
    @exams = @exams.page(params[:page]).per 10
  end

  def update
    if @exam.update_attributes exam_params
      flash[:success] = t "exams.update.success"
    else
      flash[:error] = t "exams.update.error"
    end
    redirect_to admin_exams_path
  end

  def destroy
    if @exam.destroy
      flash[:success] = t "admin.exam.flash_destroy_exam_success"
    else
      flash[:error] = t "admin.exam.flash_destroy_exam_fail"
    end
    redirect_to admin_exams_path
  end

  private
  def exam_params
    params.require(:exam).permit :status
  end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  load_and_authorize_resource

  def index
    @exam = Exam.new
    @subjects = Subject.all.select {|item| item.questions.any? }
    @exams = current_user.exams
  end

  def create
    if @exam.save
      flash[:success] = t ".success"
      redirect_to exams_path
    else
      flash[:danger] = t ".error"
    end
  end

  def show
    @exam.change_status_after_start
  end

  def update
    @exam.calculate_time
    @exam.status = :unchecked if params[:commit] == "Finish"
    if @exam.update_attributes exam_params
      flash[:success] = t ".success"
    else
      flash[:danger] = t ".error"
    end
    redirect_to exams_path
  end

  private
  def exam_params
    params.require(:exam).permit :duration, :number_of_question, :status,
    :user_id, :subject_id, results_attributes: [:id, :answer_id, :content]
  end
end

app/views/admin/exams/index.html.erb
<% provide :title, t("admin.exam.title.index") %>
<div class="row">
  <div class="col-md-12 col-md-2-offset">
    <h2><%= t "admin.exam.title.index" %></h2>
    <table class="table">
      <thead>
        <tr>
          <th><%= t"admin.exam.table.stt" %></th>
          <th><%= t"admin.exam.table.username" %></th>
          <th><%= t"admin.exam.table.subject_name" %></th>
          <th><%= t"admin.exam.table.state" %></th>
          <th><%= t"admin.exam.table.view" %></th>
          <th><%= t"admin.exam.table.delete" %></th>
        </tr>
      </thead>
      <tbody>
        <% if @exams.any? %>
          <% @exams.each_with_index do|exam, index| %>
            <tr>
              <td><%= index + 1 %></td>
              <td><%= link_to exam.user.name, admin_user_path(exam.user) %></td>
              <td><%= exam.subject.name %></td>
              <td>
                <% if exam.unchecked? %>
                  <%= form_for [:admin, exam] do |f| %>
                    <%= f.hidden_field :status, value: :checked %>
                    <%= f.submit t("admin.exam.index.btn_uncheck"), class: "btn btn-danger" %>
                  <% end %>
                <% else %>
                  <span class="label label-primary"><%= exam.status %></span>
                <% end %>
              </td>
              <td><%= link_to t("admin.exam.table.view"),
                admin_exam_path(exam), class: "btn btn-primary" %></td>
              <td><%= link_to t("delete"), [:admin, exam], method: :delete,
                data: {confirm: t("application.general.confirm_delete")},
                class: "btn btn-danger glyphicon glyphicon-trash btn-width" %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
    <%= paginate @exams %>
  </div>
</div>

app/views/admin/exams/show.html.erb
<% provide :title, t("admin.exam.title.show") %>
<div class="row">
  <div class="col-md-6 col-md-2-offset">
    <h2><%= t "admin.exam.exam_detail" %></h2>
    <table class="table">
      <tr>
        <td><strong><%= t "admin.exam.table.subject_name" %></strong></td>
        <td><%= @exam.subject.name %></td>
      </tr>
      <tr>
        <td><strong><%= t "admin.exam.table.duration" %></strong></td>
        <td><%= @exam.duration %><span><%= t "admin.exam.table.minute" %></span></td>
      </tr>
      <tr>
        <td><strong><%= t "admin.exam.table.number_question" %></strong></td>
        <td><%= @exam.number_of_question %></td>
      </tr>
      <tr>
        <td><strong><%= t "admin.exam.table.state" %></strong></td>
        <td><%= @exam.status %></td>
      </tr>
      <tr>
        <td><strong><%= t "admin.exam.table.number_correct_question" %></strong></td>
        <td><%= @exam.results.correct_answer.size %>
          <span>&#47</span><%= @exam.number_of_question%></td>
      </tr>
    </table>
  </div>
</div>