config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root "static_pages#home"
  get "static_pages/about"

  resources :users do
    resources :questions
  end
  resources :exams

  namespace :admin do
    root "users#index"
    resources :exams, only: [:show, :index, :destroy, :update]
    resources :questions
    resources :users
    resources :subjects
    resources :activities, only: [:index]
  end
end

app/views/layouts/_footer.html.erb
<div id="footer">
  <p><%= t "application.general.footer" %></p>
  <div class="nav_left">
    <%= link_to t("application.genaral.about"), static_pages_about_path, class: "about" %>
    <%= render_shareable buttons: ["twitter", "facebook", "google_plus"] %>
  </div>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse" id="navigator">
  <div class="container">
    <%= link_to t("application.general.logo"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <% if current_user.admin? %>
            <li><%= link_to t("application.general.home"), root_path %></li>
            <li><%= link_to t("application.general.exam"), admin_exams_path %></li>
            <li><%= link_to t("application.general.user"), admin_users_path %></li>
            <li><%= link_to t("application.general.question"), admin_questions_path %></li>
            <li><%= link_to t("application.general.subject"), admin_subjects_path %></li>
          <% end %>
          <% if current_user.normal? %>
            <li><%= link_to t("application.general.home"), exams_path %></li>
            <li><%= link_to t("application.general.contributte"), user_questions_path(current_user) %></li>
          <% end %>
          <li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t "application.general.account" %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <% if current_user.normal? %>
                <li><%= link_to t("application.general.profile"), edit_user_registration_path %></li>
              <% end %>
              <% if current_user.admin? %>
                <li><%= link_to t("application.general.activity_log"),  admin_activities_path %></li>
                <li><%= link_to t("application.general.profile"),  edit_user_registration_path %></li>
              <% end %>
              <li>
                <%= link_to t("application.general.logout"), destroy_user_session_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("application.general.home"), root_path %></li>
          <li><%= link_to t("users.sign_up.title"), new_user_registration_path %></li>
          <li><%= link_to t("application.general.facebook"), user_omniauth_authorize_path(:facebook) %></li>
          <li><%= link_to t("users.sign_in.title"), new_user_session_path %></li>
        <% end %>
  </div>
 </header>

app/views/layouts/application.html.erb
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": true %>
    <%= javascript_include_tag "application", "data-turbolinks-track": true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag :div, message, class: "alert alert-#{message_type}" %>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>